server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Nombre e ID del contenedor
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_id]
        target_label: container_id

      # Trae labels de Docker como labels de Loki
      - source_labels: [__meta_docker_container_label_service]
        target_label: service
      - source_labels: [__meta_docker_container_label_logging]
        target_label: logging
      - source_labels: [__meta_docker_container_label_env]
        target_label: env

    pipeline_stages:
      - docker: {}   # extrae la l√≠nea del JSON de Docker
      # Intento de parseo JSON (si no es JSON, no rompe)
      - json:
          # intenta mapear campos comunes si el log viene en JSON
          expressions:
            level: level
            msg: msg
            service: service
          on_error: "pass"   # si no es JSON, sigue
      # Promueve 'level' a label (si existe)
      - labels:
          level:
